#!/bin/bash

# Dependencias
for cmd in pan node; do
  if ! command -v $cmd &> /dev/null; then
    echo "$cmd no esta intalado"
    exit 1
  fi
done

# Constantes
ROOT_PATH="$HOME"
PROJECT_PATH="$(pwd)"
MENU_PATH="$(mktemp /tmp/comegen_menu.XXXXXX)"
MENU_ENTRY="$(mktemp /tmp/comegen_entry.XXXXXX)"
PROJECT_NAME="$(basename $(pwd))"
CONFIG_PACKAGE_MANAGER="npm"

trap 'rm -f "$MENU_PATH"' EXIT

# Iconos
I_MACHINE="󱄔"
I_TIMES=""

# Funs
## builds
build_menu() {
  cat > "$MENU_PATH" <<EOF
$I_MACHINE Build libreria
$I_MACHINE Copiar libreria en proyecto
$I_TIMES Close
EOF
}

_build_y_copiar() {
  local PROJECT_PATH
  pan log info "Build de la librería iniciado"
  pan log debug "Saltando build temporalmente"
  #pan spin -t "Buildeando la librería" -c "$CONFIG_PACKAGE_MANAGER run build:lib"
  PROJECT_PATH=$(pan file -d "$ROOT_PATH")
  pan log info "$PROJECT_PATH"
  pan log info "Build hecho"
}

# Inicio
build_menu

pan log info "Inicio"
while true; do
  pan menu -t "ComegenUI Cli Tool" "$MENU_PATH" > "$MENU_ENTRY" 2>/dev/null
  read -r ENTRY < "$MENU_ENTRY"
  case "$ENTRY" in
    "$I_MACHINE Build libreria")
      pan log info "Build de la librería iniciado"
      pan spin -t "Buildeando la librería" -c "$CONFIG_PACKAGE_MANAGER run build:lib"
      pan log info "Build hecho"
      ;;
    "$I_MACHINE Copiar libreria en proyecto")
      pan log info "Copiando la librería en un proyecto externo"
      _build_y_copiar
      break
      ;;
    "$I_TIMES Close")
      pan log info "Saliendo del script"
      break
      ;;
    *)
      pan log error "Opcion no reconocida"
      break
      ;;
  esac
done






