#!/bin/bash

# Dependencias
for cmd in pan node unzip; do
  if ! command -v $cmd &> /dev/null; then
    echo "$cmd no esta intalado"
    exit 1
  fi
done

# Constantes
ROOT_PATH="$HOME"
PROJECT_PATH="$(pwd)"
BUILD_FILE="comegenui.zip"
BUILD_PATH="$PROJECT_PATH/dist/$BUILD_FILE"
MENU_PATH="$(mktemp /tmp/comegen_menu.XXXXXX)"
MENU_ENTRY="$(mktemp /tmp/comegen_entry.XXXXXX)"
PROJECT_NAME="$(basename $(pwd))"
CONFIG_PACKAGE_MANAGER="npm"
RECENT_PATHS="$HOME/.local/share/sancho/comegenui" && mkdir -p "$RECENT_PATHS"
RECENT_PATHS_FILE="$RECENT_PATHS/recent-paths.list" && touch "$RECENT_PATHS_FILE"
HEADER_TITLE="ComegenUI Cli Tool"

trap 'rm -f "$MENU_PATH"' EXIT

# Iconos
I_MACHINE="󱄔"
I_TIMES=""
I_RECENT=""
I_FOLDER=""
I_COPY=""

# Funs
## builds
build_menu() {
  cat > "$MENU_PATH" <<EOF
$I_MACHINE Build libreria
$I_COPY Copiar libreria en proyecto
$I_TIMES Close
EOF
}

recent_paths() {
  local RECENT_OR_NEW
  local INIT_PATH="$ROOT_PATH"
  local RECENT_PATHS_FILE_TARGET="$RECENT_PATHS_FILE"
  local SELECTED
  RECENT_OR_NEW=$(pan choose -t "$1 > Path" "$I_RECENT Recientes" "$I_FOLDER Nuevo path")
  case "$RECENT_OR_NEW" in
    "$I_RECENT Recientes")
      readarray -t OPTIONS < <(grep -v "^[[:space:]]*$" "$RECENT_PATHS_FILE_TARGET")
      PROJECT_TO_COPY_PATH=$(pan filter "${OPTIONS[@]}")
      if [[ -z "$PROJECT_TO_COPY_PATH" ]]; then
        pan log error "Path no seleccionado"
        if pan confirm -t "El path esta vacio" -m "No se reconoce el path, acción cancelada. Deseas volver a menu principal?" -y "Volver" -n "Salir"; then
          return 1
        else
          exit 0
        fi
      fi
      SELECTED="$PROJECT_TO_COPY_PATH"
      ;;
    "$I_FOLDER Nuevo path")
      PROJECT_TO_COPY_PATH=$(pan file -d "$INIT_PATH")
      if [[ -z $PROJECT_TO_COPY_PATH ]]; then
        pan log error "Path no seleccionado"
        if pan confirm -t "El path esta vacio" -m "No se reconoce el path, acción cancelada. Deseas volver a menu principal?" -y "Volver" -n "Salir"; then
          return 1
        else
          exit 0
        fi
      fi
      echo "$PROJECT_TO_COPY_PATH" >> "$RECENT_PATHS_FILE_TARGET"
      SELECTED="$PROJECT_TO_COPY_PATH"
      ;;
  esac
  echo "$SELECTED"
}

_build_y_copiar() {
  local SECCION_HEADER="$HEADER_TITLE > $I_COPY Copiar lib"
  local SELECTED
  SELECTED="$(recent_paths "$SECCION_HEADER")"
  pan log info "Extrayendo la librería"
  pan spin -c "unzip -o $BUILD_PATH -d $SELECTED"
  pan log info "Extracción hecha"
}

# Inicio
build_menu

pan log info "Inicio"
while true; do
  pan menu -t "$HEADER_TITLE" "$MENU_PATH" > "$MENU_ENTRY" 2>/dev/null
  read -r ENTRY < "$MENU_ENTRY"
  case "$ENTRY" in
    "$I_MACHINE Build libreria")
      pan log info "Build de la librería iniciado"
      pan spin -t "Buildeando la librería" -c "$CONFIG_PACKAGE_MANAGER run build:lib"
      pan log info "Build hecho"
      ;;
    "$I_COPY Copiar libreria en proyecto")
      pan log info "Copiando la librería en un proyecto externo"
      _build_y_copiar
      ;;
    "$I_TIMES Close")
      pan log info "Saliendo del script"
      break
      ;;
    *)
      pan log error "Opcion no reconocida"
      break
      ;;
  esac
done






