name = "Move and Unzip"
config_file = "move_unzip_values.toml"

[[sections]]
name = "Configuration"

[[sections.fields]]
name = "Source ZIP Path"
key = "source_zip"
default = "/home/unancode/Documentos/canary/comegenUI/dist/comegenui.zip"

[[sections.fields]]
name = "Destination Path"
key = "destination_path"
default = "/home/unancode/Documentos/releases/sigacadv2/views/comegenuiv2"

[[actions]]
name = "Build Library"
command = "cd /home/unancode/Documentos/canary/comegenUI && pnpm build:lib"
confirm = true

[[actions]]
name = "Move and Unzip"
command = "rm -rf ${destination_path} && mkdir -p ${destination_path} && mv ${source_zip} ${destination_path} && unzip ${destination_path}/$(basename ${source_zip}) -d ${destination_path}"
confirm = true